# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Software Thoughts
email: omethyn@gmail.com
description: A web development blog
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://bnns.github.io" # the base hostname & protocol for your site
github_username: bnns

# Custom
version: 0.0.1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10

gems: [jekyll-paginate, kramdown]
